### PR TITLE
Creating a Branch for my stand-up log and getting my code reviewed.

### PR DESCRIPTION
**Pull request by DanyalChatha**
#TEAM PLUTO :)

### CODE REVIEW

**Review by AndrewJamesBarker — APPROVED** [review]
Looks good Danyal :)

**Comment by AndrewJamesBarker** [comment]
Oh wait, is this outside your branch? We need to create our own sub repos/branches

**Comment by AndrewJamesBarker** [comment]
We can only merge into our branches.

**Comment by DanyalChatha** [comment]
> 

I am merging my branch in the pluto main branch. Is that not the way to do it?

**Comment by simonborer** [comment]
@DanyalChatha You're correct, unless I'm missing something. Branches are for work that's unfinished. These changes look complete, so they can be merged into the main branch of the team Pluto repository.

**Comment by DanyalChatha** [comment]
> @DanyalChatha You're correct, unless I'm missing something. Branches are for work that's unfinished. These changes look complete, so they can be merged into the main branch of the team Pluto repository.

@simonborer Ok, Thank you.

**Pull request closed without merging**
